/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacionConsultas;

import componentes.Convertidor;
import componentes.Tabla;
import entities.Cliente;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class FrmConsultaGeneral extends javax.swing.JFrame {
    private String tipoDeConsulta;
    private Convertidor convertir;
    /**
     * Creates new form FrmConsultaGeneral
     */
    public FrmConsultaGeneral(String tipoDeConsulta) {
        this.tipoDeConsulta=tipoDeConsulta;
        convertir=new Convertidor();
        JOptionPane.showMessageDialog(this, "Aviso!!", "En esta pantalla van a salir todos los clientes, la tabla es para todos, y el fireado es "
                + "para ver una persona pero tambien sirve para consultarla", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(this, "Aviso!!", "No necesitas tener los dos campos llenos", JOptionPane.INFORMATION_MESSAGE);
        initComponents();
        despliegaTabla( new Tabla());
        tablaClientes();
        
    }
    public void despliegaTabla(Tabla a) {
        // Crea la tabla a partir del modelo de la tabla con los valores 
        // de los titulos de las columnas y los valores de las celdas 
        jtabla = new javax.swing.JTable(a.getModeloTabla());
        // Establece el título de la tabla 

        
        // Hace que el control del tamaño de la tabla y la porción visible 
        // lo tenga la barra de deslizamiento y no la tabla 
        jtabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtabla.setAutoscrolls(false);
        // Hace visible la tabla dentro del panel con barras de 
        // deslizamiento 
        jScrollPane1.setViewportView(jtabla);
    }
    public void tablaClientes(){
        List<Cliente> listaCl= new Dao.ClienteDAO().consultarTodos();
        if(listaCl == null || listaCl.isEmpty()){
                JOptionPane.showMessageDialog(this, "No hay Clientes registrados.","Informacion", JOptionPane.ERROR_MESSAGE);
         }
        DefaultTableModel modelo =convertir.ClienteTableModel(listaCl);
        Tabla TablaClientes=new Tabla("Lista de Clientes", modelo );
        despliegaTabla(TablaClientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnModuloLic1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnFiltrar = new javax.swing.JButton();
        btnFiltrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnModuloLic1.setBackground(new java.awt.Color(203, 77, 77));
        btnModuloLic1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnModuloLic1.setForeground(new java.awt.Color(255, 255, 255));
        btnModuloLic1.setText("Cancelar");
        btnModuloLic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloLic1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consulta de Licencia");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText(" Nombre Completo");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RFC");

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtRFC.setBackground(new java.awt.Color(255, 255, 255));
        txtRFC.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        txtRFC.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        btnFiltrar.setBackground(new java.awt.Color(51, 143, 193));
        btnFiltrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnFiltrar1.setBackground(new java.awt.Color(69, 156, 81));
        btnFiltrar1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnFiltrar1.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrar1.setText("Consultar");
        btnFiltrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel2)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addComponent(txtRFC)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnModuloLic1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFiltrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnModuloLic1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(txtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFiltrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModuloLic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloLic1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnModuloLic1ActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        Cliente cliente = null;
        
            if(txtRFC.getText() != null){
                String regex = "^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$";
                Pattern pattern = Pattern.compile(regex);
                Matcher matcher = pattern.matcher(txtRFC.getText().toUpperCase());
                if(matcher.matches()){
                    //cliente=new Dao.ClienteDAO().consultaRFC(txtRFC.getText());
                    
                    List<Cliente> cs= new ArrayList<Cliente>();
                    //List<Cliente> listaCl= new Dao.ClienteDAO().consultarTodos();
                    Cliente sg=new Dao.ClienteDAO().consultaRFC(txtRFC.getText());
                    //Cliente sd=new Cliente();
                    cs.add(sg);
                    /*for (int i = 0; i < listaCl.size(); i++) {
                        sd= listaCl.get(i);
                        if(sd.getRfc()==txtRFC.getText()){
                            cs.add(new Dao.ClienteDAO().consultar(sd.getId_Cliente()));
                            
                        }
                    }*/
                    
                    if(cs==null || cs.isEmpty()){
                        JOptionPane.showMessageDialog(this, "No existe el Cliente", "Advertencia!!", JOptionPane.INFORMATION_MESSAGE);
                    }
                    DefaultTableModel modelo =convertir.ClienteTableModel(cs);
                    despliegaTabla( new Tabla());
                    Tabla TablaClientes=new Tabla("Lista de Clientes", modelo );
                    despliegaTabla(TablaClientes);
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Advertencia!!", "La el RFC no es Valido", JOptionPane.INFORMATION_MESSAGE);
                }
            }
//            else if(txtRFC.getText() == null && txtNombre.getText() != null){
//                //cliente=new Dao.ClienteDAO().consultaNombre(txtNombre.getText());
//                List<Cliente> cs= new ArrayList<Cliente>();
//                List<Cliente> css= new Dao.ClienteDAO().consultarTodos();
//                Cliente sg=new Cliente();
//                for (int i = 0; i < css.size(); i++) {
//                    Cliente sd= css.get(i);
//                    if(sd.getNombreCompleto()==txtNombre.getText()){
//                        cs.add(new Dao.ClienteDAO().consultar(sd.getId_Cliente()));
//                    }
//                }
//                cs.add(new Dao.ClienteDAO().consultar(sg.getId_Cliente()));
//                if(cs==null || cs.isEmpty()){
//                    JOptionPane.showMessageDialog(this, "No existe el Cliente", "Advertencia!!", JOptionPane.INFORMATION_MESSAGE);
//                }
//                DefaultTableModel modelo =convertir.ClienteTableModel(cs);
//                despliegaTabla( new Tabla());
//                Tabla TablaClientes=new Tabla("Lista de Clientes", modelo );
//                despliegaTabla(TablaClientes);
//            }
        
//        List<Cliente> lista=new ArrayList<Cliente>();
//        lista.add(cliente);
//        DefaultTableModel modelo =convertir.ClienteTableModel(lista);
//        Tabla TablaClientes=new Tabla("Lista de Clientes", modelo );
//        despliegaTabla(TablaClientes);
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnFiltrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrar1ActionPerformed
        // TODO add your handling code here:
        //FrmCostosPlacas frm=new FrmCostosPlacas(cliente, tipoDeConsulta);
        //frm.setVisible(true);
        Cliente cliente = null;
        
        if(txtRFC.getText() != null ){
            String regex = "^[A-Z&Ñ]{3,4}[0-9]{6}[A-Z0-9]{3}$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(txtRFC.getText().toUpperCase());
            if(matcher.matches()){
                List<Cliente> cs= new ArrayList<Cliente>();
                //List<Cliente> listaCl= new Dao.ClienteDAO().consultarTodos();
                Cliente sg=new Dao.ClienteDAO().consultaRFC(txtRFC.getText());
                //Cliente sd=new Cliente();
                cs.add(sg);
                FrmCostosPlacas frm=new FrmCostosPlacas(sg, tipoDeConsulta);
                frm.setVisible(true);
                dispose();

            
//        }else{
//            //cliente=new Dao.ClienteDAO().consultaNombre(txtNombre.getText());
//            List<Cliente> cs= new ArrayList<Cliente>();
//            List<Cliente> css= new Dao.ClienteDAO().consultarTodos();
//            Cliente sg=new Cliente();
//            for (int i = 0; i < css.size(); i++) {
//                Cliente sd=css.get(i);
//                if(sd.getNombreCompleto()==txtNombre.getText()){
//                    sg=css.get(i);
//                }
//            }
//            cs.add(sg);
//            
//            FrmCostosPlacas frm=new FrmCostosPlacas(sg, tipoDeConsulta);
//            frm.setVisible(true);
//            dispose();
          }

        }
        
    }//GEN-LAST:event_btnFiltrar1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnFiltrar1;
    private javax.swing.JButton btnModuloLic1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables
private javax.swing.JTable jtabla;
}
