/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacionConsultas;

import componentes.Convertidor;
import componentes.Tabla;
import entities.AdquiereLiciencia;
import entities.Automovil;
import entities.Cliente;
import entities.Empaca;
import entities.Vehiculo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class FrmCostosPlacas extends javax.swing.JFrame {
    private Cliente cliente;
    private String tipoDeConsulta;
    private Convertidor convertir;
    private Empaca emplaca;
    private AdquiereLiciencia adq;
    /**
     * Creates new form FrmCostosPlacas
     */
    public FrmCostosPlacas(Cliente cliente, String tipoDeConsulta) {
        this.cliente=cliente;
        this.tipoDeConsulta=tipoDeConsulta;
        initComponents();
        if(tipoDeConsulta=="Licencia"){
            jLabel1.setText("Consulta de Licencias");
            tablaClientesAquisicionLiciencia();
        }else{
            jLabel1.setText("Consulta de Placas Compradas");
            tablaClientesEmplaca();
        }
    }
    
    public void tablaClientesEmplaca(){
        //Vehiculo veh=new Automovil();
        //emplaca=cliente
        List<Cliente> lsita=new ArrayList<Cliente>();
        lsita.add(cliente);
        List<Automovil> listaA=new Dao.AutomovilDAO().consultaClientesAd(lsita);
        List<Empaca> listaE=new Dao.EmpacaDAO().consultarAutomoviles(listaA);
        if(listaE == null || listaE.isEmpty()){
                JOptionPane.showMessageDialog(this, "No hay Placas Compradas.","Informacion", JOptionPane.ERROR_MESSAGE);
         }
        DefaultTableModel modelo =convertir.EmplacaTableModel(listaE);
        Tabla TablaClientes=new Tabla("Lista de Cliente que Tienen una Placa Comprada", modelo );
        despliegaTabla(TablaClientes);
    }
    public void tablaClientesAquisicionLiciencia(){
        adq= cliente.getAdquiereLicienciaCliente();
        List<Cliente> lsita=new ArrayList<Cliente>();
        lsita.add(cliente);
        
        List<AdquiereLiciencia> listaAdL= new Dao.AdquiereLicenciaDAO().consultaClientesAd(lsita);
        if(listaAdL == null || listaAdL.isEmpty()){
                JOptionPane.showMessageDialog(this, "No hay Clientes registrados.","Informacion", JOptionPane.ERROR_MESSAGE);
         }
        DefaultTableModel modelo =convertir.AquiereLicenTableModel(listaAdL);
        Tabla TablaClientes=new Tabla("Lista de Cliente que tienen Licencia", modelo );
        despliegaTabla(TablaClientes);
        
    }

    public void despliegaTabla(Tabla a) {
        // Crea la tabla a partir del modelo de la tabla con los valores 
        // de los titulos de las columnas y los valores de las celdas 
        jtabla = new javax.swing.JTable(a.getModeloTabla());
        // Establece el título de la tabla 

        
        // Hace que el control del tamaño de la tabla y la porción visible 
        // lo tenga la barra de deslizamiento y no la tabla 
        jtabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtabla.setAutoscrolls(false);
        // Hace visible la tabla dentro del panel con barras de 
        // deslizamiento 
        jScrollPane1.setViewportView(jtabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Consulta de ");

        btnBuscar.setBackground(new java.awt.Color(128, 140, 146));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Cerrar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private javax.swing.JTable jtabla;
}
